title: RiTUAL Group at MBZUAI
description: >-
  A simple Jekyll site for an academic research group with pages for the home
  page, team, publications, news and a dedicated leader profile. Content is
  stored in Markdown or YAML files so that updates can be made without
  editing HTML.
baseurl: "/web" # the subpath where the site will be deployed (e.g. /web for https://yourname.github.io/web)
url: "https://ritual-mbzuai.github.io" # the base hostname & protocol for your site
markdown: kramdown

# Disable the default GitHub Pages theme. Without this setting, GitHub Pages
# automatically applies the `jekyll-theme-primer` which expects bootstrap
# partials to be available. Our site provides its own layouts and styles, so we
# explicitly disable the theme.
theme: null

# Collections can be defined here if you wish to create a collection of
# documents. For this simple site we are using data files instead.