title: Research Group
description: >-
  A simple Jekyll site for an academic research group with pages for the home
  page, team, publications, news and a dedicated leader profile. Content is
  stored in Markdown or YAML files so that updates can be made without
  editing HTML.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
markdown: kramdown

# Collections can be defined here if you wish to create a collection of
# documents. For this simple site we are using data files instead.